"use client";
import { useMemo, useRef } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { useGSAP } from "@gsap/react";
import { gsap } from "gsap";
import { Crosshair, Maximize2, Minus, MousePointer2, Plus } from "lucide-react";
import { attentionMatrix, seeded, tokenize } from "@/math/attention";
import { useStudioStore } from "@/stores/studio-store";
import { IconButton } from "@/components/ui";

const vector = (seed: number) => Array.from({ length: 8 }, (_, index) => Math.round(20 + seeded(seed, index) * 75));
function Token({ label, index, kind = "input" }: { label: string; index: number; kind?: string }) { const { selectedToken, selectToken, pinToken, pinnedTokens } = useStudioStore(); const active = index === selectedToken; return <button onClick={() => selectToken(index)} onDoubleClick={() => pinToken(index)} aria-pressed={active} aria-label={`Focus token ${label}, position ${index + 1}. Double click to pin.`} className={`token token-${kind} ${active ? "selected" : ""} ${pinnedTokens.includes(index) ? "pinned" : ""}`}><span>{label}</span><i>{index}</i></button>; }
function AttentionGraph() { const { input, selectedToken, progress, sceneId } = useStudioStore(); const tokens = tokenize(input); const cells = useMemo(() => attentionMatrix(tokens, sceneId === "masked"), [tokens, sceneId]); const row = cells[selectedToken] ?? []; return <div className="attention-graph"><svg viewBox="0 0 760 340" role="img" aria-label="Attention relationships from selected token"><defs><linearGradient id="edge" x1="0" x2="1"><stop stopColor="#a78bfa"/><stop offset="1" stopColor="#22d3ee"/></linearGradient></defs>{row.map((cell) => { const sourceX = 380; const sourceY = 275; const targetX = 76 + cell.target * (608 / Math.max(1, tokens.length - 1)); const opacity = Math.max(.12, cell.weight * 2.5); return <motion.path key={cell.target} d={`M ${sourceX} ${sourceY} Q ${(sourceX + targetX) / 2} 120 ${targetX} 74`} fill="none" stroke="url(#edge)" strokeWidth={1 + cell.weight * 10} strokeOpacity={opacity} initial={{ pathLength: 0 }} animate={{ pathLength: progress > .18 ? 1 : 0 }} transition={{ duration: .65, delay: cell.target * .04 }} />; })}</svg><div className="target-tokens">{tokens.map((token, index) => <Token key={`${token}-${index}`} label={token} index={index} />)}</div><div className="source-token"><Token label={tokens[selectedToken] ?? "<start>"} index={selectedToken} kind="query"/><span>querying context</span></div></div> }
function Heatmap() { const { input, selectedToken, selectToken, sceneId } = useStudioStore(); const tokens = tokenize(input); const matrix = attentionMatrix(tokens, sceneId === "masked"); return <div className="heatmap-wrap"><div className="heatmap-label">K →</div><div className="heatmap">{matrix.flatMap((row, source) => row.map((cell) => <button key={`${source}-${cell.target}`} onClick={() => selectToken(source)} aria-label={`${tokens[source]} attends to ${tokens[cell.target]} with weight ${cell.weight.toFixed(2)}`} className={source === selectedToken ? "matrix-cell selected-row" : "matrix-cell"} style={{ backgroundColor: `rgb(108 92 ${Math.round(120 + cell.weight * 135)} / ${0.25 + cell.weight * .75})` }}><span>{cell.weight.toFixed(2)}</span></button>))}</div><div className="matrix-axis">Q ↓ &nbsp; Each row sums to 1.00</div></div> }
function Vectors({ title = "Embedding lookup" }: { title?: string }) { const { input, selectedToken, positionalEncoding } = useStudioStore(); const tokens = tokenize(input); const values = vector(selectedToken); return <div className="vectors"><div className="vector-title"><span>{title}</span><b>{tokens[selectedToken] ?? "input"}</b></div><div className="bars">{values.map((value, index) => <motion.div key={index} className="vector-bar" animate={{ height: `${value}%` }} transition={{ type: "spring", stiffness: 160, damping: 18, delay: index * .025 }}><span>{index + 1}</span></motion.div>)}</div>{positionalEncoding && <div className="position-signal">+ positional signal <span>sin/cos({selectedToken + 1})</span></div>}</div> }
function Architecture() { const { layers, heads, sceneId } = useStudioStore(); return <div className="architecture"><div className="arch-side"><span>INPUT</span><div className="mini-tokens"><i/><i/><i/><i/><i/></div></div><div className="blocks">{Array.from({ length: Math.min(layers, 6) }, (_, index) => <motion.div key={index} className={`transformer-block ${sceneId === "encoder" ? "lit" : ""}`} initial={{ opacity: 0, y: 24 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: index * .07 }}><b>Encoder {index + 1}</b><span>{heads} heads · Add & Norm</span><div><i/><i/><i/></div></motion.div>)}</div><div className="arch-side"><span>CONTEXT</span><div className="context-orb"/></div></div> }
function Generation() { const { progress } = useStudioStore(); const text = ["<START>", "The", "cat", "sat", "on", "the", "mat"]; const count = Math.max(1, Math.ceil(progress * (text.length - 1))); return <div className="generation"><div className="decoder-label">DECODER LOOP · t = {count}</div><div className="generated-line">{text.slice(0, count + 1).map((word, index) => <motion.span key={word} initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: index * .08 }}>{word}</motion.span>)}<span className="caret"/></div><div className="vocab-bars">{["mat", "rug", "floor", "quietly", "today"].map((word, index) => <div key={word}><span>{word}</span><i style={{ width: `${Math.max(8, 83 - index * 17 + Math.sin(progress * 8 + index) * 8)}%` }}/><b>{(0.57 / (index + 1)).toFixed(2)}</b></div>)}</div></div> }
function TokenInspector() { const { input, selectedToken, sceneId, positionalEncoding } = useStudioStore(); const tokens = tokenize(input); const row = attentionMatrix(tokens, sceneId === "masked")[selectedToken] ?? []; const strongest = row.reduce((best, item) => item.weight > best.weight ? item : best, row[0]); const values = vector(selectedToken); return <section className="token-inspector" aria-label="Selected token details"><div><span className="inspector-label">ACTIVE REPRESENTATION</span><strong>“{tokens[selectedToken] ?? "<start>"}”</strong><small>token id {1000 + selectedToken * 137} · position {selectedToken + 1}</small></div><div className="inspector-vector" aria-label="Eight dimensional contextual vector">{values.map((value, index) => <i key={index} style={{ height: `${value}%` }}/>)}</div><div className="inspector-relationship"><span>Strongest context</span><b>{tokens[strongest?.target ?? selectedToken] ?? "—"}</b><small>{((strongest?.weight ?? 0) * 100).toFixed(1)}% attention {positionalEncoding ? "· position encoded" : "· order disabled"}</small></div></section> }
export function VisualStage() { const { sceneId, progress, cameraZoom, cameraFocus, input, zoomIn, zoomOut, fitCamera } = useStudioStore(); const root = useRef<HTMLDivElement>(null); const tokenCount = tokenize(input).length; const focalOffset = cameraFocus === null || tokenCount < 2 ? 0 : ((cameraFocus / (tokenCount - 1)) - .5) * -74; useGSAP(() => { gsap.to(".ambient-orb", { x: 22, y: -16, duration: 4, repeat: -1, yoyo: true, ease: "sine.inOut" }); }, { scope: root }); const isAttention = ["attention", "qkv", "softmax", "masked", "cross"].includes(sceneId); const isMatrix = ["matrix", "heads"].includes(sceneId); const isGeneration = ["decoder", "projection", "generation"].includes(sceneId); return <main ref={root} className="visual-stage" aria-live="polite"><div className="stage-top"><div><span className="status-dot"/> LIVE SIMULATION</div><span>Frame {String(Math.round(progress * 144)).padStart(3, "0")}</span></div><div className="ambient-orb orb-a"/><div className="ambient-orb orb-b"/><div className="camera-frame"><AnimatePresence mode="wait"><motion.div key={sceneId} className="scene-canvas camera-viewport" initial={{ opacity: 0, scale: .98, y: 12 }} animate={{ opacity: 1, scale: cameraZoom, x: focalOffset, y: 0 }} exit={{ opacity: 0, scale: 1.01, y: -8 }} transition={{ type: "spring", stiffness: 210, damping: 26 }}>{isAttention ? <AttentionGraph/> : isMatrix ? <Heatmap/> : isGeneration ? <Generation/> : sceneId === "encoder" || sceneId === "pipeline" ? <Architecture/> : <Vectors title={sceneId === "position" ? "Embedding + position" : sceneId === "ffn" ? "Expand → activate → compress" : "Embedding lookup"}/>}</motion.div></AnimatePresence></div><TokenInspector/><div className="stage-hint"><MousePointer2 size={14}/> Click a token to move camera focus <div className="camera-controls" aria-label="Camera controls"><IconButton onClick={zoomOut} aria-label="Zoom out"><Minus size={15}/></IconButton><IconButton onClick={zoomIn} aria-label="Zoom in"><Plus size={15}/></IconButton><IconButton onClick={fitCamera} aria-label="Fit visualization"><Maximize2 size={15}/></IconButton><IconButton onClick={fitCamera} aria-label="Center camera"><Crosshair size={15}/></IconButton></div></div></main>; }
